[project]
name = "tripmate"
version = "0.1.0"
description = "multi agent trip planner"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
packages = ["src"] # Or list your actual package name if it's different